### ISSUE TITLE
Add Ingest Script with Vector Embedding

### ISSUE THREAD

**Issue by zach-blumenfeld** [neo4j-product-examples/graphrag-examples#1]

**Comment by Rasputin2** [comment]
Hi Zach - I listened to your demo on Thursday and have been trying to get your repo running locally using my own Aura database and openAI subscription.  But I am running into this issue:

![image](https://github.com/neo4j-product-examples/graphrag-examples/assets/43117960/2acd2a8c-4550-4b2c-9b0e-2e1af36d0dff)

**Comment by zach-blumenfeld** [comment]
closing with #2
